title: Yu Dong
description: Data Analyst at Ancestry, USC MS Business Analytics Alumni
author: Yu Dong
theme: jekyll-theme-slate

- title: Home
  url: /
  sublinks:
    - title: Projects
      url: /projects
    - title: Blog
      url: /blogs
