# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yu Dong's Blog
email:
description: Data Science & Analytics, Data Storyteller
twitter_username: username
github_username: yudong-94
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "UA-112502179-1"
    anonymize_ip         : false

author:
  name   : "Yu Dong"
  avatar : "/assets/images/bio_photo.jpg"
  bio    : "Data Science & Analytics, Data Storyteller"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/yudong1994/"
    - label: "GitHub"
      url: "https://github.com/yudong-94"

footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/yudong1994/"
    - label: "GitHub"
      url: "https://github.com/yudong-94"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _posts/projects/data_viz
  - scope:
      path: "_posts/projects/data_viz"
      type: posts
    values:
      layout: single
      author_profile: false #do not show weekly viz on homepage
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
